export const ADD_MASTER_ACTION = {
    ACTION_GET_CITIES: 'ACTION_GET_CITIES(Master)',
    ACTION_WRITE_NAME: 'ACTION_WRITE_NAME(Master)',
    ACTION_WRITE_SURNAME: 'ACTION_WRITE_SURNAME(Master)',
    ACTION_CHOOSE_RATING: 'ACTION_CHOOSE_RATING(Master)',
    ACTION_CHOOSE_CITY: 'ACTION_CHOOSE_CITY(Master)'
};

