export const ADD_ORDER_ACTION = {
	ACTION_GET_CITIES: 'ACTION_GET_CITIES(Order)',
	ACTION_GET_PRODUCTS: 'ACTION_GET_PRODUCTS(Order)',
	ACTION_GET_MASTERS: 'ACTION_GET_MASTER(Order)',
	ACTION_WRITE_NAME: 'ACTION_WRITE_NAME(Order)',
	ACTION_WRITE_EMAIL: 'ACTION_WRITE_EMAIL',
	ACTION_CHOOSE_PRODUCT: 'ACTION_CHOOSE_PRODUCT(Order)',
	ACTION_CHOOSE_CITY: 'ACTION_CHOOSE_CITY(Order)',
	ACTION_CHOOSE_MASTER: 'ACTION_CHOOSE_MASTER(Order)',
	ACTION_CHOOSE_DATETIME: 'ACTION_CHOOSE_DATETIME(Order)',
	ACTION_CHOOSE_SIZE: 'ACTION_CHOOSE_SIZE(Order)'
};

