export const ADD_ACTION_MASTER = {
    ACTION_GET_CITIES: 'ACTION_GET_CITIES',
    ACTION_WRITE_NAME: 'ACTION_WRITE_NAME',
    ACTION_WRITE_SURNAME: 'ACTION_WRITE_SURNAME',
    ACTION_CHOOSE_RATING: 'ACTION_CHOOSE_RATING',
    ACTION_CHOOSE_CITY: 'ACTION_CHOOSE_CITY'
};

