export const EDIT_ACTION_MASTER = {
    ACTION_GET_CITIES: 'ACTION_GET_CITIES(EDIT)',
    ACTION_WRITE_NAME: 'ACTION_WRITE_NAME(EDIT)',
    ACTION_WRITE_SURNAME: 'ACTION_WRITE_SURNAME(EDIT)',
    ACTION_CHOOSE_RATING: 'ACTION_CHOOSE_RATING(EDIT)',
    ACTION_CHOOSE_CITY: 'ACTION_CHOOSE_CITY(EDIT)',
    ACTION_ON_EDIT_MASTER: 'ACTION_ON_EDIT_MASTER(EDIT)'
};
