export const EDIT_ORDER_ACTION = {
	ACTION_GET_CITIES: 'ACTION_GET_CITIES(Order_edit)',
	ACTION_GET_PRODUCTS: 'ACTION_GET_PRODUCTS(Order_edit)',
	ACTION_GET_MASTERS: 'ACTION_GET_MASTER(Order_edit)',

	ACTION_WRITE_CLIENT: 'ACTION_WRITE_CLIENT(Order_edit)',
	ACTION_WRITE_EMAIL: 'ACTION_WRITE_EMAIL(Order_edit)',
	ACTION_CHOOSE_PRICE: 'ACTION_CHOOSE_PRICE(Order_edit)',
	ACTION_CHOOSE_SIZE: 'ACTION_CHOOSE_SIZE(Order_edit)',
	ACTION_CHOOSE_DATETIME: 'ACTION_CHOOSE_DATETIME(Order_edit)',

	ACTION_CHOOSE_CITY_ID: 'ACTION_CHOOSE_CITY_ID(Order_edit)',
	ACTION_CHOOSE_MASTER_ID: 'ACTION_CHOOSE_MASTER_ID(Order_edit)',
	ACTION_CHOOSE_PRODUCT_ID: 'ACTION_CHOOSE_PRODUCT_ID(Order_edit)',

	ACTION_ON_EDIT_ORDER: 'ACTION_ON_EDIT_ORDER(Order_edit)'
};

