export const EDIT_CLIENT_ACTION = {
    ACTION_GET_CITIES: 'ACTION_GET_CITIES(CLIENT)',
    ACTION_WRITE_NAME: 'ACTION_WRITE_NAME(CLIENT)',
    ACTION_WRITE_EMAIL: 'ACTION_WRITE_EMAIL(CLIENT)',
    ACTION_CHOOSE_CITY: 'ACTION_CHOOSE_CITY(CLIENT)',
    ACTION_ON_EDIT_CLIENT: 'ACTION_ON_EDIT_CLIENT(CLIENT)'
};
